package com.fortysevendeg.android.sqlite.statement

import java.io.{InputStream, Reader}
import java.math.BigDecimal
import java.net.URL
import java.sql._
import java.util.Calendar

import com.fortysevendeg.android.sqlite.{SQLDroidConnection, _}
import com.fortysevendeg.android.sqlite.logging.{AndroidLogWrapper, LogWrapper}
import com.fortysevendeg.android.sqlite.util.StreamUtils._
import StatementInfo._

import scala.util.{Failure, Success, Try}

class SQLDroidPreparedStatement(
  val sql: String,
  sqlDroidConnection: SQLDroidConnection,
  val columnGenerated: Option[String] = None,
  arguments: PreparedStatementArguments = new PreparedStatementArguments,
  logWrapper: LogWrapper = new AndroidLogWrapper())
  extends SQLDroidStatement(sqlDroidConnection, columnGenerated, logWrapper)
  with PreparedStatement {

  val notInPreparedErrorMessage = "This method cannot be called on a PreparedStatement"

  val maximumSizeErrorMessage = "Byte maximum exceeded"

  val invalidLengthErrorMessage = (s: Long) => s"Invalid length: $s"

  val executingSQLErrorMessage = (s: String) => s"Error executing statement $s"

  override def executeQuery(sql: String): ResultSet =
    throw new SQLException(notInPreparedErrorMessage)

  override def executeUpdate(sql: String): Int =
    throw new SQLException(notInPreparedErrorMessage)

  override def executeUpdate(sql: String, autoGeneratedKeys: Int): Int =
    throw new SQLException(notInPreparedErrorMessage)

  override def executeUpdate(sql: String, columnIndexes: scala.Array[Int]): Int =
    throw new SQLException(notInPreparedErrorMessage)

  override def executeUpdate(sql: String, columnNames: scala.Array[String]): Int =
    throw new SQLException(notInPreparedErrorMessage)

  override def execute(sql: String): Boolean =
    throw new SQLException(notInPreparedErrorMessage)

  override def execute(sql: String, autoGeneratedKeys: Int): Boolean =
    throw new SQLException(notInPreparedErrorMessage)

  override def execute(sql: String, columnIndexes: scala.Array[Int]): Boolean =
    throw new SQLException(notInPreparedErrorMessage)

  override def execute(sql: String, columnNames: scala.Array[String]): Boolean =
    throw new SQLException(notInPreparedErrorMessage)

  override def addBatch(sql: String): Unit =
    throw new SQLException(notInPreparedErrorMessage)

  override def addBatch(): Unit =
    arguments.addNewEntry()

  override def clearParameters(): Unit =
    arguments.clearArguments()

  override def execute(): Boolean =
    executeWithArgs(sql, Some(arguments))

  override def executeQuery(): ResultSet =
    executeQueryWithArgs(sql, Some(arguments))

  override def executeUpdate(): Int =
    executeUpdateWithArgs(sql, Some(arguments))

  override def executeBatch(): scala.Array[Int] = withOpenConnection { db =>
    val updateArray = arguments map { array =>
      Try(db.execSQL(sql, array)) match {
        case Success(_) if isChange(sql) =>
          db.changedRowCount()
        case Success(_) =>
          Statement.SUCCESS_NO_INFO
        case Failure(e) =>
          logWrapper.e(executingSQLErrorMessage(sql), Some(e))
          Statement.EXECUTE_FAILED
      }
    }
    updateCount = updateArray filter (_ > 0) reduceOption (_ + _)
    updateArray.toArray
  }

  override def setBinaryStream(parameterIndex: Int, x: InputStream): Unit =
    setBinaryStream(parameterIndex, x, Integer.MAX_VALUE)

  override def setBinaryStream(parameterIndex: Int, x: InputStream, length: Int): Unit =
    ifNonEmptyAndValidLength(parameterIndex, x, length) { (arg, l) =>
      setBytes(parameterIndex, inputStreamToByteArray(arg, length))
    }

  override def setBinaryStream(parameterIndex: Int, x: InputStream, length: Long): Unit =
    ifNonEmptyAndValidLength(parameterIndex, x, length) { (arg, l) =>
      setBytes(parameterIndex, inputStreamToByteArray(arg, l))
    }

  override def setBlob(parameterIndex: Int, inputStream: InputStream): Unit =
    setBinaryStream(parameterIndex, inputStream)

  override def setBlob(parameterIndex: Int, inputStream: InputStream, length: Long): Unit =
    setBinaryStream(parameterIndex, inputStream, length)

  override def setBlob(parameterIndex: Int, x: Blob): Unit =
    ifNonEmpty(parameterIndex, x) { arg =>
      validateLength(arg.length()) match {
        case Some(msg) =>
          throw new SQLException(msg)
        case None =>
          arguments.setArgument(parameterIndex, x.getBytes(1, arg.length().toInt))
      }
    }

  override def setBoolean(parameterIndex: Int, x: Boolean): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setByte(parameterIndex: Int, x: Byte): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setBytes(parameterIndex: Int, x: scala.Array[Byte]): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setClob(parameterIndex: Int, x: Reader): Unit =
    ifNonEmpty(parameterIndex, x) { arg =>
      setString(parameterIndex, readerToString(arg))
    }

  override def setClob(parameterIndex: Int, x: Reader, length: Long): Unit =
    ifNonEmptyAndValidLength(parameterIndex, x, length) { (arg, l) =>
      setString(parameterIndex, readerToString(arg, l))
    }

  override def setClob(parameterIndex: Int, x: Clob): Unit =
    ifNonEmpty(parameterIndex, x) { arg =>
      validateLength(arg.length()) match {
        case Some(msg) =>
          throw new SQLException(msg)
        case None =>
          setString(parameterIndex, x.getSubString(1l, arg.length().toInt))
      }
    }

  override def setDate(parameterIndex: Int, x: Date): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setDate(parameterIndex: Int, x: Date, cal: Calendar): Unit =
    logWrapper.notImplemented(arguments.setArgument(parameterIndex, x))

  override def setDouble(parameterIndex: Int, x: Double): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setFloat(parameterIndex: Int, x: Float): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setInt(parameterIndex: Int, x: Int): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setLong(parameterIndex: Int, x: Long): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setNull(parameterIndex: Int, sqlType: Int): Unit =
    arguments.setObjectArgument(parameterIndex, javaNull)

  override def setNull(parameterIndex: Int, sqlType: Int, typeName: String): Unit =
    arguments.setObjectArgument(parameterIndex, javaNull)

  override def setObject(parameterIndex: Int, x: scala.Any): Unit =
    arguments.setObjectArgument(parameterIndex, x)

  override def setObject(parameterIndex: Int, x: scala.Any, targetSqlType: Int): Unit =
    arguments.setObjectArgument(parameterIndex, x)

  override def setObject(parameterIndex: Int, x: scala.Any, targetSqlType: Int, scaleOrLength: Int): Unit =
    arguments.setObjectArgument(parameterIndex, x)

  override def setShort(parameterIndex: Int, x: Short): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setString(parameterIndex: Int, x: String): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setTime(parameterIndex: Int, x: Time): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setTime(parameterIndex: Int, x: Time, cal: Calendar): Unit =
    logWrapper.notImplemented(arguments.setArgument(parameterIndex, x))

  override def setTimestamp(parameterIndex: Int, x: Timestamp): Unit =
    arguments.setArgument(parameterIndex, x)

  override def setTimestamp(parameterIndex: Int, x: Timestamp, cal: Calendar): Unit =
    logWrapper.notImplemented(arguments.setArgument(parameterIndex, x))

  override def getMetaData: ResultSetMetaData =
    logWrapper.notImplemented(javaNull)

  override def getParameterMetaData: ParameterMetaData =
    logWrapper.notImplemented(javaNull)

  override def setArray(parameterIndex: Int, x: Array): Unit =
    logWrapper.notImplemented(Unit)

  override def setAsciiStream(parameterIndex: Int, x: InputStream): Unit =
    logWrapper.notImplemented(Unit)

  override def setAsciiStream(parameterIndex: Int, x: InputStream, length: Int): Unit =
    logWrapper.notImplemented(Unit)

  override def setAsciiStream(parameterIndex: Int, x: InputStream, length: Long): Unit =
    logWrapper.notImplemented(Unit)

  override def setBigDecimal(parameterIndex: Int, x: BigDecimal): Unit =
    logWrapper.notImplemented(Unit)

  override def setCharacterStream(parameterIndex: Int, reader: Reader): Unit =
    logWrapper.notImplemented(Unit)

  override def setCharacterStream(parameterIndex: Int, reader: Reader, length: Int): Unit =
    logWrapper.notImplemented(Unit)

  override def setCharacterStream(parameterIndex: Int, reader: Reader, length: Long): Unit =
    logWrapper.notImplemented(Unit)

  override def setNCharacterStream(parameterIndex: Int, value: Reader): Unit =
    logWrapper.notImplemented(Unit)

  override def setNCharacterStream(parameterIndex: Int, value: Reader, length: Long): Unit =
    logWrapper.notImplemented(Unit)

  override def setNClob(parameterIndex: Int, reader: Reader): Unit =
    logWrapper.notImplemented(Unit)

  override def setNClob(parameterIndex: Int, reader: Reader, length: Long): Unit =
    logWrapper.notImplemented(Unit)

  override def setNClob(parameterIndex: Int, value: NClob): Unit =
    logWrapper.notImplemented(Unit)

  override def setNString(parameterIndex: Int, value: String): Unit =
    logWrapper.notImplemented(Unit)

  override def setRef(parameterIndex: Int, x: Ref): Unit =
    logWrapper.notImplemented(Unit)

  override def setRowId(parameterIndex: Int, x: RowId): Unit =
    logWrapper.notImplemented(Unit)

  override def setSQLXML(parameterIndex: Int, xmlObject: SQLXML): Unit =
    logWrapper.notImplemented(Unit)

  override def setURL(parameterIndex: Int, x: URL): Unit =
    logWrapper.notImplemented(Unit)

  override def setUnicodeStream(parameterIndex: Int, x: InputStream, length: Int): Unit =
    logWrapper.notImplemented(Unit)

  private[this] def ifNonEmpty[T](parameterIndex: Int, arg: T)(f: T => Unit) =
    Option(arg) match {
      case Some(a) => f(a)
      case None => arguments.setObjectArgument(parameterIndex, javaNull)
    }

  private[this] def ifNonEmptyAndValidLength[T](parameterIndex: Int, arg: T, length: Long)(f: (T, Int) => Unit) =
    ifNonEmpty(parameterIndex, arg) { a =>
      validateLength(length) match {
        case Some(msg) => throw new SQLException(msg)
        case _ => f(a, length.toInt)
      }
    }

  private[this] def validateLength(length: Long): Option[String] = {
    length match {
      case i if i < 0 =>
        Some(invalidLengthErrorMessage(i))
      case i if i > Int.MaxValue =>
        Some(maximumSizeErrorMessage)
      case _ =>
        None
    }
  }
}
